// proto/model.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.0
// source: proto/model.proto

package model

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelStreamer_StreamData_FullMethodName = "/model.ModelStreamer/StreamData"
)

// ModelStreamerClient is the client API for ModelStreamer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelStreamerClient interface {
	// 客户端流式RPC（Python -> Golang）
	StreamData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DataChunk, DataSummary], error)
}

type modelStreamerClient struct {
	cc grpc.ClientConnInterface
}

func NewModelStreamerClient(cc grpc.ClientConnInterface) ModelStreamerClient {
	return &modelStreamerClient{cc}
}

func (c *modelStreamerClient) StreamData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DataChunk, DataSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ModelStreamer_ServiceDesc.Streams[0], ModelStreamer_StreamData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataChunk, DataSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelStreamer_StreamDataClient = grpc.ClientStreamingClient[DataChunk, DataSummary]

// ModelStreamerServer is the server API for ModelStreamer service.
// All implementations must embed UnimplementedModelStreamerServer
// for forward compatibility.
type ModelStreamerServer interface {
	// 客户端流式RPC（Python -> Golang）
	StreamData(grpc.ClientStreamingServer[DataChunk, DataSummary]) error
	mustEmbedUnimplementedModelStreamerServer()
}

// UnimplementedModelStreamerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelStreamerServer struct{}

func (UnimplementedModelStreamerServer) StreamData(grpc.ClientStreamingServer[DataChunk, DataSummary]) error {
	return status.Errorf(codes.Unimplemented, "method StreamData not implemented")
}
func (UnimplementedModelStreamerServer) mustEmbedUnimplementedModelStreamerServer() {}
func (UnimplementedModelStreamerServer) testEmbeddedByValue()                       {}

// UnsafeModelStreamerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelStreamerServer will
// result in compilation errors.
type UnsafeModelStreamerServer interface {
	mustEmbedUnimplementedModelStreamerServer()
}

func RegisterModelStreamerServer(s grpc.ServiceRegistrar, srv ModelStreamerServer) {
	// If the following call pancis, it indicates UnimplementedModelStreamerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelStreamer_ServiceDesc, srv)
}

func _ModelStreamer_StreamData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ModelStreamerServer).StreamData(&grpc.GenericServerStream[DataChunk, DataSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModelStreamer_StreamDataServer = grpc.ClientStreamingServer[DataChunk, DataSummary]

// ModelStreamer_ServiceDesc is the grpc.ServiceDesc for ModelStreamer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelStreamer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "model.ModelStreamer",
	HandlerType: (*ModelStreamerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamData",
			Handler:       _ModelStreamer_StreamData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/model.proto",
}
